// <auto-generated />
using System;
using ApiServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250315130509_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiServer.Database.Models.Devices", b =>
                {
                    b.Property<Guid>("deviceGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("deviceGuid");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ApiServer.Database.Models.Movements", b =>
                {
                    b.Property<Guid>("movementGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Device")
                        .HasColumnType("uuid");

                    b.Property<bool>("Entry")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("movementGuid");

                    b.ToTable("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
